// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TGProyecto.UnitTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// CrearDepartamento - Use 'CrearDepartamentoParams' to pass parameters into this method.
        /// </summary>
        public void CrearDepartamento()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIHomePageMyASPNETMVCAWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uICreateMyASPNETMVCAppDocument = this.UIHomePageMyASPNETMVCAWindow.UIChromeLegacyWindowWindow.UICreateMyASPNETMVCAppDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIHomePageMyASPNETMVCAWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(153, 175));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(86, 413));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(119, 434));

            // Type '{CapsLock}' in 'Create - My ASP.NET MVC Application - Google Chrom...' document
            Keyboard.SendKeys(uICreateMyASPNETMVCAppDocument, this.CrearDepartamentoParams.UICreateMyASPNETMVCAppDocumentSendKeys, ModifierKeys.None);

            // Type 'R{CapsLock}iberl{Back}alta' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.CrearDepartamentoParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(212, 525));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(63, 500));
        }
        
        #region Properties
        public virtual CrearDepartamentoParams CrearDepartamentoParams
        {
            get
            {
                if ((this.mCrearDepartamentoParams == null))
                {
                    this.mCrearDepartamentoParams = new CrearDepartamentoParams();
                }
                return this.mCrearDepartamentoParams;
            }
        }
        
        public UIHomePageMyASPNETMVCAWindow UIHomePageMyASPNETMVCAWindow
        {
            get
            {
                if ((this.mUIHomePageMyASPNETMVCAWindow == null))
                {
                    this.mUIHomePageMyASPNETMVCAWindow = new UIHomePageMyASPNETMVCAWindow();
                }
                return this.mUIHomePageMyASPNETMVCAWindow;
            }
        }
        #endregion
        
        #region Fields
        private CrearDepartamentoParams mCrearDepartamentoParams;
        
        private UIHomePageMyASPNETMVCAWindow mUIHomePageMyASPNETMVCAWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CrearDepartamento'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class CrearDepartamentoParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{CapsLock}' in 'Create - My ASP.NET MVC Application - Google Chrom...' document
        /// </summary>
        public string UICreateMyASPNETMVCAppDocumentSendKeys = "{CapsLock}";
        
        /// <summary>
        /// Type 'R{CapsLock}iberl{Back}alta' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "R{CapsLock}iberl{Back}alta";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHomePageMyASPNETMVCAWindow : WinWindow
    {
        
        public UIHomePageMyASPNETMVCAWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - My ASP.NET MVC Application - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Home Page - My ASP.NET MVC Application - Google Chrome");
            this.WindowTitles.Add("Index - My ASP.NET MVC Application - Google Chrome");
            this.WindowTitles.Add("Create - My ASP.NET MVC Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "14558304";
            this.WindowTitles.Add("Home Page - My ASP.NET MVC Application - Google Chrome");
            this.WindowTitles.Add("Index - My ASP.NET MVC Application - Google Chrome");
            this.WindowTitles.Add("Create - My ASP.NET MVC Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Home Page - My ASP.NET MVC Application - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Index - My ASP.NET MVC Application - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Create - My ASP.NET MVC Application - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        
        public WinControl UICreateMyASPNETMVCAppDocument
        {
            get
            {
                if ((this.mUICreateMyASPNETMVCAppDocument == null))
                {
                    this.mUICreateMyASPNETMVCAppDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUICreateMyASPNETMVCAppDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUICreateMyASPNETMVCAppDocument.WindowTitles.Add("Create - My ASP.NET MVC Application - Google Chrome");
                    #endregion
                }
                return this.mUICreateMyASPNETMVCAppDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create - My ASP.NET MVC Application - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        
        private WinControl mUICreateMyASPNETMVCAppDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
